# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:
  docker_build:
    runs-on: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v4

      - name: build image
        run: |
          docker buildx build -t cnegovik/helloworld:${{ github.event.head_commit.message }} -t helloworld:latest .
          docker push cnegovik/helloworld:${{ github.event.head_commit.message }}
  docker_run:
    runs-on: dev
    needs: docker_build

    steps:
    
      - name: Run docker compose
        run: |
          cd
          docker compose up -d
          docker system prune -af
      
      - name: check connectivity
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://localhost"]'
          expected: '[301, 200]'
